export default {
    LOADING: 'LOADING',
    SUCCESS: 'SUCCESS',
    CHANGE_FIELDS: 'CHANGE_FIELDS',
    CHANGE_DEFAULTS: 'CHANGE_DEFAULTS',
    CHANGE_MAPS: 'CHANGE_MAPS',
    CHANGE_PICKERS: 'CHANGE_PICKERS',
    CHANGE_VISIBILITY_TRIGGERS: 'CHANGE_VISIBILITY_TRIGGERS',
    CHANGE_SINGULAR_NAME: 'CHANGE_SINGULAR_NAME',
    CHANGE_MODE: 'CHANGE_MODE',
    CHANGE_DATA_PROPERTY: 'CHANGE_DATA_PROPERTY',
    CHANGE_API_URL: 'CHANGE_API_URL',
    API_CALLING: 'API_CALLING',
    API_CALL: 'API_CALL'
};
