
export default {
    SUCCESS: 'SUCCESS',
    REFRESH: 'REFRESH',
    LOADING: 'LOADING',
    CHANGE_LIMIT: 'CHANGE_LIMIT',
    CHANGE_PAGE: 'CHANGE_PAGE',
    CHANGE_TOOL_FILTER: 'CHANGE_TOOL_FILTER',
    CHANGE_QUERY_FILTER: 'CHANGE_QUERY_FILTER',
    CHANGE_FIELDS: 'CHANGE_FIELDS',
    CHANGE_MAPS: 'CHANGE_MAPS',
    CHANGE_SINGULAR_NAME: 'CHANGE_SINGULAR_NAME',
    CHANGE_API_URL: 'CHANGE_API_URL'
  };
